[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.0.0"
authors = ["Teoh Han Hui <teohhanhui@gmail.com>"]
edition = "2021"
rust-version = "1.80.0"
description = "WIP"
repository = "https://github.com/teohhanhui/hexciv"
license = "MIT OR Apache-2.0"

[workspace.dependencies]

[workspace.lints.clippy]
arithmetic_side_effects = "warn"
